#!/usr/bin/env python3
"""
convert_images.py - Convert PNG icons in icons/ to C byte arrays in tqt/putty_icons.h
Modeled after /home/cdef/_PROJETS/yabatman/convert_images.py
"""

import os
import sys

def process_file(filepath, varname):
    basename = os.path.basename(filepath)
    with open(filepath, 'rb') as f:
        data = f.read()

    output = f"// Data for {basename} ({len(data)} bytes)\n"
    output += f"static const unsigned char {varname}_data[] = {{\n    "

    for i, b in enumerate(data):
        output += f"0x{b:02x}, "
        if (i + 1) % 12 == 0:
            output += "\n    "

    output += "\n};\n"
    output += f"static const size_t {varname}_size = sizeof({varname}_data);\n\n"
    return output

def main():
    base_dir = os.path.dirname(os.path.abspath(__file__))
    icons_dir = os.path.join(base_dir, "icons")
    out_file = os.path.join(base_dir, "tqt", "putty_icons.h")

    if not os.path.isdir(icons_dir):
        print(f"Error: icons directory not found at {icons_dir}")
        sys.exit(1)

    header = """/*
 * putty_icons.h - Embedded window and application icons
 * Auto-generated by convert_images.py from icons/puttycfg.png and icons/putty.png
 */
#ifndef PUTTY_ICONS_H
#define PUTTY_ICONS_H

#include <stddef.h>
#include <tqpixmap.h>
#include <tqimage.h>

"""

    # Check icons
    puttycfg_png = os.path.join(icons_dir, "puttycfg.png")
    putty_png = os.path.join(icons_dir, "putty.png")

    if os.path.isfile(puttycfg_png):
        header += process_file(puttycfg_png, "puttycfg")
    else:
        print(f"Warning: {puttycfg_png} not found")

    if os.path.isfile(putty_png):
        header += process_file(putty_png, "putty")
    else:
        print(f"Warning: {putty_png} not found")

    header += """
static inline TQPixmap get_puttycfg_icon()
{
    TQImage img;
    if (img.loadFromData(puttycfg_data, (int)puttycfg_size, "PNG"))
        return TQPixmap(img);
    return TQPixmap();
}

static inline TQPixmap get_putty_icon()
{
    TQImage img;
    if (img.loadFromData(putty_data, (int)putty_size, "PNG"))
        return TQPixmap(img);
    return TQPixmap();
}

#endif /* PUTTY_ICONS_H */
"""

    with open(out_file, "w") as f:
        f.write(header)

    print(f"Generated {out_file} successfully.")

if __name__ == "__main__":
    main()
